<a href="https://colab.research.google.com/github/Anyapara/pytorch-Tutorialcodemy/blob/main/intro_to_colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np

In [7]:
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
#reshape and view
my_torch = my_torch.reshape(2,5)
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [9]:
my_torch = my_torch.reshape(5,-1)
my_torch

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [10]:
#slices
my_torch7 =torch.arange(10)
my_torch7


tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
my_torch7[7]

tensor(7)

In [13]:
 my_torch8 = my_torch7.reshape(5,2)
 my_torch8

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [20]:
my_torch8[:,1:]


tensor([[1],
        [3],
        [5],
        [7],
        [9]])